### ISSUE TITLE
how to run it offline?

### ISSUE THREAD

**Issue by Norbtails97** [PenguinMod/penguinmod.github.io#43] opened 2024-02-23 20:29 UTC
GoGuardian is slowing Penguinmod down on my PC. how do I run it offline using a .HTML file? i can't localhost on a school Chromebook. PLS HELP!

**Comment by JeremyGamer13** [comment] 2024-02-23 20:47
it wouldnt work fully offline but i might start building penguinmod to HTML and releasing it at some point for chromebooks

**Comment by Norbtails97** [comment] 2024-02-23 20:52
good idea. thank you JGamer

**Comment by RedMan13** [comment] 2024-02-23 20:54
> GoGuardian is slowing Penguinmod down on my PC. how do I run it offline using a .HTML file? i can't localhost on a school Chromebook. PLS HELP!

it could just be that your on a chromebook, as penguinmod runs somewhat slow for me too on a completely stock chromebook

**Comment by Norbtails97** [comment] 2024-02-23 20:57
no it like freezes for a few seconds then kick in and repeat after 10 seconds

**Comment by RedMan13** [comment] 2024-02-23 20:57
oh bru

**Comment by JeremyGamer13** [comment] 2024-02-23 20:58
goguardian tends to do that yea, not sure if html build would help but ill make one later anyway

**Comment by JeremyGamer13** [comment] 2024-02-23 20:59
actually i wonder if or how we could edit the github action to automatically release the site build as an html file on github

**Comment by RedMan13** [comment] 2024-02-23 20:59
idk if you can get it all into a single html file because of how all the webpack stuff is setup

**Comment by RedMan13** [comment] 2024-02-23 21:00
and yeah im pretty sure you could do dat

**Comment by JeremyGamer13** [comment] 2024-02-23 21:00
well not 1 html file but like a zip or just in folders

**Comment by Norbtails97** [comment] 2024-02-23 21:00
that with the index.html file works :D

**Comment by IceandFire04** [comment] 2024-04-23 20:41
this may be the most based suggestion

**Comment by davidctinescu** [comment] 2024-05-15 15:46
> it wouldnt work fully offline but i might start building penguinmod to HTML and releasing it at some point for chromebooks

what if you make penguinmod in penguinmod and package it using penguinmod :trollface:

**Comment by davidctinescu** [comment] 2024-05-15 15:48
> well not 1 html file but like a zip or just in folders

wont `npm build` or something like that build it into static webpage or something like that

**Comment by RedMan13** [comment] 2024-05-15 16:43
> > well not 1 html file but like a zip or just in folders
> 
> wont `npm build` or something like that build it into static webpage or something like that

no :skull:

**Comment by davidctinescu** [comment] 2024-05-17 05:43
> > > well not 1 html file but like a zip or just in folders
> > 
> > 
> > wont `npm build` or something like that build it into static webpage or something like that
> 
> no 💀

yes lol run `npm run build` and it will generate static html files 💀

**Comment by RedMan13** [comment] 2024-05-17 06:22
> > > > well not 1 html file but like a zip or just in folders
> > > 
> > > 
> > > wont `npm build` or something like that build it into static webpage or something like that
> > 
> > 
> > no 💀
> 
> yes lol run `npm run build` and it will generate static html files 💀

that is infact not what you said, you said "it will make a static **webpage**" implying that the action makes the server host too 🤓

**Comment by davidctinescu** [comment] 2024-05-22 12:02
> > > > > well not 1 html file but like a zip or just in folders
> > > > 
> > > > 
> > > > wont `npm build` or something like that build it into static webpage or something like that
> > > 
> > > 
> > > no 💀
> > 
> > 
> > yes lol run `npm run build` and it will generate static html files 💀
> 
> that is infact not what you said, you said "it will make a static **webpage**" implying that the action makes the server host too 🤓

nerd but it still works if you run it using a python http server via crostini or whatever the feature to get linux packages on chromeos is

**Comment by RedMan13** [comment] 2024-05-22 18:17
> nerd but it still works if you run it using a python http server via crostini or whatever the feature to get linux packages on chromeos is

that is not a step any sane user would go to

**Comment by davidctinescu** [comment] 2024-05-23 11:17
> that is not a step any sane user would go to

i made an offline editor anyways, currently its windows and linux

**Comment by SharkPool-SP** [comment] 2024-07-17 07:38
Duplicate of: https://github.com/PenguinMod/PenguinMod-Vm/issues/35

Check there for updates. Closing this

**Closed as not planned by SharkPool-SP** 2024-07-17 07:38 UTC
